# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /cygdrive/c/Users/patri/AppData/Local/JetBrains/CLion2021.2/cygwin_cmake/bin/cmake.exe

# The command to remove a file.
RM = /cygdrive/c/Users/patri/AppData/Local/JetBrains/CLion2021.2/cygwin_cmake/bin/cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /cygdrive/c/Users/patri/OneDrive/Desktop/Projects/IC/ES

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /cygdrive/c/Users/patri/OneDrive/Desktop/Projects/IC/ES

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/cygdrive/c/Users/patri/AppData/Local/JetBrains/CLion2021.2/cygwin_cmake/bin/cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/cygdrive/c/Users/patri/AppData/Local/JetBrains/CLion2021.2/cygwin_cmake/bin/cmake.exe -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /cygdrive/c/Users/patri/OneDrive/Desktop/Projects/IC/ES/CMakeFiles /cygdrive/c/Users/patri/OneDrive/Desktop/Projects/IC/ES//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /cygdrive/c/Users/patri/OneDrive/Desktop/Projects/IC/ES/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ES

# Build rule for target.
ES: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ES
.PHONY : ES

# fast build rule for target.
ES/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ES.dir/build.make CMakeFiles/ES.dir/build
.PHONY : ES/fast

ESAlgorithm.o: ESAlgorithm.cpp.o
.PHONY : ESAlgorithm.o

# target to build an object file
ESAlgorithm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ES.dir/build.make CMakeFiles/ES.dir/ESAlgorithm.cpp.o
.PHONY : ESAlgorithm.cpp.o

ESAlgorithm.i: ESAlgorithm.cpp.i
.PHONY : ESAlgorithm.i

# target to preprocess a source file
ESAlgorithm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ES.dir/build.make CMakeFiles/ES.dir/ESAlgorithm.cpp.i
.PHONY : ESAlgorithm.cpp.i

ESAlgorithm.s: ESAlgorithm.cpp.s
.PHONY : ESAlgorithm.s

# target to generate assembly for a file
ESAlgorithm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ES.dir/build.make CMakeFiles/ES.dir/ESAlgorithm.cpp.s
.PHONY : ESAlgorithm.cpp.s

Individual.o: Individual.cpp.o
.PHONY : Individual.o

# target to build an object file
Individual.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ES.dir/build.make CMakeFiles/ES.dir/Individual.cpp.o
.PHONY : Individual.cpp.o

Individual.i: Individual.cpp.i
.PHONY : Individual.i

# target to preprocess a source file
Individual.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ES.dir/build.make CMakeFiles/ES.dir/Individual.cpp.i
.PHONY : Individual.cpp.i

Individual.s: Individual.cpp.s
.PHONY : Individual.s

# target to generate assembly for a file
Individual.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ES.dir/build.make CMakeFiles/ES.dir/Individual.cpp.s
.PHONY : Individual.cpp.s

grn_eval.o: grn_eval.c.o
.PHONY : grn_eval.o

# target to build an object file
grn_eval.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ES.dir/build.make CMakeFiles/ES.dir/grn_eval.c.o
.PHONY : grn_eval.c.o

grn_eval.i: grn_eval.c.i
.PHONY : grn_eval.i

# target to preprocess a source file
grn_eval.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ES.dir/build.make CMakeFiles/ES.dir/grn_eval.c.i
.PHONY : grn_eval.c.i

grn_eval.s: grn_eval.c.s
.PHONY : grn_eval.s

# target to generate assembly for a file
grn_eval.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ES.dir/build.make CMakeFiles/ES.dir/grn_eval.c.s
.PHONY : grn_eval.c.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ES.dir/build.make CMakeFiles/ES.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ES.dir/build.make CMakeFiles/ES.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ES.dir/build.make CMakeFiles/ES.dir/main.cpp.s
.PHONY : main.cpp.s

ode.o: ode.c.o
.PHONY : ode.o

# target to build an object file
ode.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ES.dir/build.make CMakeFiles/ES.dir/ode.c.o
.PHONY : ode.c.o

ode.i: ode.c.i
.PHONY : ode.i

# target to preprocess a source file
ode.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ES.dir/build.make CMakeFiles/ES.dir/ode.c.i
.PHONY : ode.c.i

ode.s: ode.c.s
.PHONY : ode.s

# target to generate assembly for a file
ode.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ES.dir/build.make CMakeFiles/ES.dir/ode.c.s
.PHONY : ode.c.s

read.o: read.cpp.o
.PHONY : read.o

# target to build an object file
read.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ES.dir/build.make CMakeFiles/ES.dir/read.cpp.o
.PHONY : read.cpp.o

read.i: read.cpp.i
.PHONY : read.i

# target to preprocess a source file
read.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ES.dir/build.make CMakeFiles/ES.dir/read.cpp.i
.PHONY : read.cpp.i

read.s: read.cpp.s
.PHONY : read.s

# target to generate assembly for a file
read.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ES.dir/build.make CMakeFiles/ES.dir/read.cpp.s
.PHONY : read.cpp.s

rk4.o: rk4.c.o
.PHONY : rk4.o

# target to build an object file
rk4.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ES.dir/build.make CMakeFiles/ES.dir/rk4.c.o
.PHONY : rk4.c.o

rk4.i: rk4.c.i
.PHONY : rk4.i

# target to preprocess a source file
rk4.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ES.dir/build.make CMakeFiles/ES.dir/rk4.c.i
.PHONY : rk4.c.i

rk4.s: rk4.c.s
.PHONY : rk4.s

# target to generate assembly for a file
rk4.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ES.dir/build.make CMakeFiles/ES.dir/rk4.c.s
.PHONY : rk4.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ES"
	@echo "... ESAlgorithm.o"
	@echo "... ESAlgorithm.i"
	@echo "... ESAlgorithm.s"
	@echo "... Individual.o"
	@echo "... Individual.i"
	@echo "... Individual.s"
	@echo "... grn_eval.o"
	@echo "... grn_eval.i"
	@echo "... grn_eval.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... ode.o"
	@echo "... ode.i"
	@echo "... ode.s"
	@echo "... read.o"
	@echo "... read.i"
	@echo "... read.s"
	@echo "... rk4.o"
	@echo "... rk4.i"
	@echo "... rk4.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

